name: Windows Server with ngrok
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup ngrok and tmate
      run: |
        # دانلود ngrok
        Invoke-WebRequest -Uri "https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip" -OutFile ngrok.zip
        Expand-Archive -Path ngrok.zip -DestinationPath ngrok
        $env:Path += ";$PWD/ngrok"

        # تنظیم Authtoken ngrok
        $env:NGROK_AUTH_TOKEN = "${{ secrets.NGROK_AUTH_TOKEN }}"
        .\ngrok\ngrok.exe authtoken $env:NGROK_AUTH_TOKEN

        # دانلود و استخراج tmate
        Invoke-WebRequest -Uri "https://github.com/tmate-io/tmate/releases/download/2.4.0/tmate-2.4.0-static-win64.zip" -OutFile tmate.zip
        Expand-Archive -Path tmate.zip -DestinationPath tmate
        $env:Path += ";$PWD/tmate"

        # اجرای ngrok و tmate
        Start-Process -NoNewWindow .\ngrok\ngrok.exe tcp 3389
        Start-Process -NoNewWindow .\tmate\tmate.exe

        # نگه داشتن Workflow فعال
        while ($true) { Start-Sleep -Seconds 3600 }
      shell: powershell
