name: Ubuntu Server with ngrok
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install ngrok and SSH
      run: |
        # نصب openssh-server
        sudo apt-get update
        sudo apt-get install -y openssh-server

        # دانلود و نصب ngrok
        wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip
        unzip ngrok-v3-stable-linux-amd64.zip
        chmod +x ngrok
        ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

        # اجرای ngrok با تونل HTTP (برای تست)
        ./ngrok http 80 &

        # فعال‌سازی SSH و نگه داشتن سرور فعال
        sudo service ssh start
        sudo tail -f /dev/null
      shell: bash
